### ISSUE TITLE
Groups in Light Entities

### ISSUE THREAD

**Issue by xbmcnut** [BeardedTinker/Home-Assistant_Config#1]
Hey @BeardedTinker 

Thanks for sharing your code. I wondered why you have groups defined in your lights folder rather than in your groups folder?

**Comment by BeardedTinker** [comment]
Thanks for asking! 
If I remember correctly, there was change in HA at one point in regard to that.
This allows me to have group of lights represented as light too so I can use commands that apply to lights with them![Light-group](https://user-images.githubusercontent.com/47822612/89259016-b496b400-d629-11ea-9fd4-1b64f5c87180.jpg)
Before this change in HA, I did have them as standard group, but when they changed something, they stopped working or I wasn't able to control them with Google Assistant.

**Comment by xbmcnut** [comment]
Thanks. I just wondered with all of your tidy up why those light groups weren't actually defined in our entities/groups folder?

**Comment by BeardedTinker** [comment]
I don't think that it worked in groups folder, as they were in a fact lights - and that's the only reason I had to put them in /entities/lights. 
There was breaking change with groups/lights about year ago that forced me to do something quickly and this is result.

**Comment by xbmcnut** [comment]
Thanks. All good. How long did the total conversion take and is there a chance you could document your transition steps? (unless you have a video coming) :)

**Comment by BeardedTinker** [comment]
I did that very slowly - couple of weekends, few hours every night and a lot of restarts. 
You got me thinking to make a video on that.

**Comment by BeardedTinker** [comment]
Finished recording and editing the video. It is currently out as preview to channel members but will be out publicly tomorrow @xbmcnut .
Link to it is: https://youtu.be/kgFwhYInzfA 
I really would like to hear your comment on this as it took so long to record and unfortunately video is also very long (too long).
There are timestamps (or better to say will be when I finish with video description) for points of interest in video.
