### ISSUE TITLE
Support for roon in music assistant??

### ISSUE THREAD

**Issue by platini76** [BeardedTinker/Home-Assistant_Config#103]
hello, it is possible to configure roon as provider and player?
thanks for your work

**Comment by BeardedTinker** [comment]
> hello, it is possible to configure roon as provider and player?
> thanks for your work

Thanks for the question.
For now, no. There is a feature request for it a few months old, but not sure if it's getting worked on or not.

https://github.com/orgs/music-assistant/discussions/1120

**Comment by platini76** [comment]
hello! nice to know you..
why it is so difficult? roon has many possibility to work with.. also extensions..
and maybe it is also dlna (not sure)

**Comment by BeardedTinker** [comment]
There are too many possible providers for MA - DLNA would be best bet to get most of them working.
Just look at main ones - Plex, Emby, JellyFin + Roon as you mentioned and it's still jsut few of the available.
If DLNA would work it would allow most of them to be providers without the need to build specific connectors.

**Comment by platini76** [comment]
but also roon is well connected with home assistant...

**Comment by BeardedTinker** [comment]
I can't help with this. You could try asking original author on MA GitHub repository.
Will be closing this issue as I can't add anything extra here.
Thanks for opening issue and asking.
