### ISSUE TITLE
Media Control device Apple TV) refresh issue

### ISSUE THREAD

**Issue by markandersonus** [BeardedTinker/Home-Assistant_Config#112]
Media display is constantly redrawing

YAML:
cards:
  - type: media-control
    entity: media_player.living_room_appletv

https://github.com/BeardedTinker/Home-Assistant_Config/assets/3257799/99819475-ec00-4e41-837f-af536eea0174

On latest version of HA and Room Card

**Comment by BeardedTinker** [comment]
Hi! Thanks for creating the issue.
There is known issue for Room-Card.  As far as I know, there is no fix for now except using older version.
You can check the whole thread here:
https://github.com/marcokreeft87/room-card/issues/283
