### ISSUE TITLE
Add GitHub workflow/actions

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#21]
Will add GitHub actions/workflow to test configuration not by Travis CI (or not only by Travis CI) but also with GitHub CI.

Possible enhancement could be to add testing against BETA and DEV version too - similar what @frenck has in his repository.

**Comment by BeardedTinker** [comment]
OK, I've been fighting with this for some time now...
The problem is paths... 

```
/usr/bin/docker run --name homeassistanthomeassistantstable_b54071 --label aac2aa --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Home-Assistant_Config/Home-Assistant_Config":"/github/workspace" homeassistant/home-assistant:stable python -m homeassistant --config ./ --script check_config --info all
Testing configuration at /github/workspace/./
Failed config
  homeassistant: 
    - not a directory @ data['allowlist_external_dirs'][0]
    - allowlist_external_dirs: [source /github/workspace/./configuration.yaml:10]
        - /config/tmp
```
Tried following:
```
          sudo mkdir -p /config/tmp
          sudo mkdir -p config/tmp
          sudo mkdir -p ./config/tmp
```
And none of that is working.
The "easy" fix would be to completely redo my Home Assistant and GitHub repository, change all paths, move everything to /config folder... But that's easy in theory in practice I would have to redo all from scratch.

Probably easy fix, but I have no clue what to do next...

**Comment by frenck** [comment]
A neat little trick / workaround is to put those folders into your secrets file. While not a secret, they can be swapped out during CI using a secrets stub file

**Comment by BeardedTinker** [comment]
Wow, that really is a great trick! Never thought of that!

**Comment by BeardedTinker** [comment]
Thanks to the great tip, this is now fixed. Added a bit of complexity, but now both Travis CI and GitHub CI are working, with GitHub one also checking against Beta and Dev versions!
