### ISSUE TITLE
lovelace info

### ISSUE THREAD

**Issue by ranrinc** [BeardedTinker/Home-Assistant_Config#39]
Hi there,

Is there any way that we can view your lovelace setup? Thanks

**Comment by BeardedTinker** [comment]
Thanks for asking! I'm looking in a way how to post everything and keep it easy to manage.
Probably for now will just copy "RAW yaml" until I figure better option (will do it tomorrow).

**Comment by ranrinc** [comment]
thanks

**Comment by BeardedTinker** [comment]
I've added yaml files here - they are listed in commit above and you can find them also linked in issue #40
