### ISSUE TITLE
Question: use now() or sensor.date

### ISSUE THREAD

**Issue by metbril** [BeardedTinker/Home-Assistant_Config#47]
Nice trick, this sensor.

I was just wondering. Wouldn't using `now()` be evaluating every minute, and using the `sensor.date` entity be evaluating just once a day?

https://github.com/BeardedTinker/Home-Assistant_Config/blob/0ff7960b353db79270fb2d3f0c8d2efd45e4e25f/entities/sensors/today.yaml#L10

Another value_template could be:

```yaml
value_template: >
  {% set w = strptime(states('sensor.date'), '%Y-%m-%d').strftime('%w') | int %}
  {{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][w]}}
```

Not as clean but less resource consuming.

**Comment by metbril** [comment]
> You can use issues to ask for clarification, make a suggestion or just leave a comment.

Sorry to see no response at all.

**Comment by BeardedTinker** [comment]
Sorry for this - obviously hiccup from my side - I did write a very long response, but probably never hit submit/comment button :)

Yes, you are correct about `now() `vs `sensor.date`
I will be implementing your suggestion for using sensor.date.

At one point I had a good reason to keep it like this, but that is now gone :) 

I should probably go through all of the code and track other time/date usage in there.
