### ISSUE TITLE
Lastseen Zigbee notification

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#53]
Thanks for @deadly667 for this.

This binary sensor and automation is precaution for possible issues with Zigbee devices dropping of the network or not responding for longer period of time.

Will be using this to track and alert me if there are any issues:
https://community.home-assistant.io/t/script-to-check-last-seen-zigbee-devices/155571/9?u=beardedconti

**Comment by deadly667** [comment]
I set that it looks for devices which last seen time is longer then 24 hours. But you can change it to whatever you like :)
Time is in seconds (24 * 60 * 60).

**Comment by BeardedTinker** [comment]
Was looking at that and 24hrs is OK - not too long, but still god for some of my pasive devices (buttons).
I have one that responds in less then 24hrs so should be OK for now!

**Comment by BeardedTinker** [comment]
![Screenshot_20210422_192946.jpg](https://user-images.githubusercontent.com/47822612/115760096-40f82b00-a3a1-11eb-961f-10813725b082.jpg)
Nice! I call this issue officially closed!
