### ISSUE TITLE
2021.8 Energy monitoring

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#69]
In terms of Shelly EM and Utilities meter I have, they work great.
I was able to add directly Shelly EM to Energy tab, but also, I managed to get peak/off peak energy sensors. And those are now used.

In terms of price/cost - this is different story.
I used legacy (how they are now called) template sensors, and it didn't want to work.
Problem is missing `state_class: measurement` that is missing and also not supported here.

In order to do that, I had to create new style template sensors that now track peak, off peak and also total for daily and monthly power cost.

**Comment by hvddrift** [comment]
Hi,

I use your config (and videos) as my leaning and inspiration guide.

I am trying to add a template for my Shelly em3 (to make a total of 3 inputs)

The below code works when it is the native "configeration.yaml" but not in a directory like yours.

Any suggestions?

`template:
  sensor:
    - name: "Power Total"
      unique_id: power_total
      state: >-
        {{ (states('sensor.shellyem3_c45bbe603440_channel_a_power')|float + 
            states('sensor.shellyem3_c45bbe603440_channel_b_power')|float + 
            states('sensor.phase_c_power')|float) }}
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      attributes:
        last_reset: '2018-08-06T00:00:00+00:00'
    - name: "Power Factor Total"
      unique_id: power_factor_total
      state: >-
        {{ (((states('sensor.shellyem3_c45bbe603440_channel_a_power')|float) * (states('sensor.shellyem3_c45bbe603440_channel_a_power_factor')|float) +
              (states('sensor.shellyem3_c45bbe603440_channel_b_power')|float) * (states('sensor.shellyem3_c45bbe603440_channel_b_power_factor')|float) +
              (states('sensor.shellyem3_c45bbe603440_channel_c_power')|float) * (states('sensor.shellyem3_c45bbe603440_channel_c_power_factor')|float)) /
            (states('sensor.shellyem3_c45bbe603440_channel_a_power')|float + states('sensor.shellyem3_c45bbe603440_channel_b_power')|float + states('ensor.shellyem3_c45bbe603440_channel_c_power')|float))
            |int }}
      unit_of_measurement: "%"
      device_class: power_factor
      state_class: measurement
      attributes:
        last_reset: '2018-08-06T00:00:00+00:00'`

**Comment by hvddrift** [comment]
This code looks better here:

https://community.home-assistant.io/t/shelly-3em-3-phases-energy-sensor/328166/6?u=hans_van_der_drift
