### ISSUE TITLE
Klipper/Moonraker HA integration

### ISSUE THREAD

**Issue by BeardedTinker** [BeardedTinker/Home-Assistant_Config#72]
Since I was bored and decided to ditch Marlin, here is new Ender 3 Pro integration for Home Assistant.
Thanks to @pedrolamas for pointing me in [right direction](https://github.com/Arksine/moonraker/blob/master/docs/example-home-assistant.yaml). 

So far only sensors have been added.

To do list:
- add webcam stream to HA frontend
- change slicer to one that creates preview
- embed preview in HA frontend

**Comment by pedrolamas** [comment]
Well, in that case you might want to take a look at this PR with an improved version that includes control of relays! https://github.com/Arksine/moonraker/pull/222

**Comment by BeardedTinker** [comment]
This need GPIO to be enabled on RPI? Plus [power] section in printer.cfg?

Hopefully I'll be able to tackle that later in the afternoon...

**Comment by pedrolamas** [comment]
I didn't enable anything on my Pi, but you might need to do it on yours... yes, you do need one `[power]` section for each switch you have (also on my repo)

**Comment by BeardedTinker** [comment]
@pedrolamas - with curent change to mpeg and generic cameras (as of HA 2022.4), how did you solve GCode preview?

I was using:
```
platform: generic
name: V24 GCode Preview
still_image_url: >
  {% if states.sensor.gcode_preview.attributes["relative_path"] == "" %}
      https://192.168.1.201:8123/local/no_preview.png
  {% else %}
      http://192.168.1.167:7125/server/files/gcodes/{{ states.sensor.gcode_preview.attributes["relative_path"] }}
  {% endif %}
scan_interval: 5
content_type: image/png
```
And of course it didn't migrate to UI configuration because, yeah.
Was trying http://192.168.1.167:7125/server/files/gcodes/{{ states.sensor.gcode_preview.attributes["relative_path"] }} as path for still image, but it of course fails as it's not able to resolve this path...
![image](https://user-images.githubusercontent.com/47822612/162686102-0d3fcf2b-effa-4e7c-9878-fecf2b0d92b4.png)

**Comment by pedrolamas** [comment]
I wasn't showing the G-code Preview on mine just the regular camera preview, but let me take a look and see what I can find!

These changes away from YAML are a PITA... 😕

**Comment by pedrolamas** [comment]
According to the [updated docs](https://www.home-assistant.io/integrations/generic/#configuration), "Templates are allowed in the URL fields..." so this should still work fine!

You might want to try it as a single template expression:

```
{{ 'https://192.168.1.201:8123/local/no_preview.png' if states.sensor.gcode_preview.attributes['relative_path'] == '' else 'http://192.168.1.167:7125/server/files/gcodes/' ~ states.sensor.gcode_preview.attributes['relative_path'] }}
```

**Comment by BeardedTinker** [comment]
Sorry, just managed to finish my work day.
Still not working... It does see that it's not empty but it doesn't resolve filename...
I think I know what the problem is - empty spaces in filename (yeah I know, BAD practice)... Will try when I get home.
Currently sitting in car with laptop in lap :)

**Comment by BeardedTinker** [comment]
This has been fixed now. Not even sure what or if I did something. :)
