### ISSUE TITLE
oled esp32 board not supported?

### ISSUE THREAD

**Issue by Tom-Neverwinter** [BeardedTinker/Home-Assistant_Config#78]
https://github.com/SensorsIot/Geiger-Counter-RadiationD-v1.1-CAJOE-

since these are both very similar projects, I'm coming from that project board is also not supported?

```
Using 'COM8' as serial port.
Connecting.........
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting.........
Detecting chip type... ESP32
Connecting....

Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32-D0WDQ6 (revision 1)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
 - MAC Address: C4:4F:33:0C:2F:ED
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
 - Flash Size: 4MB
Unexpected error: The firmware binary is invalid (magic byte=23, should be E9)

```

**Comment by BeardedTinker** [comment]
What board is this - ESP32 with screen? Need to check PINs. It should work if proper board is selected I think.

When compiling with Arduino IDE, you need to find correct board library and install it there.

ESPHome that I used in Geiger project, should support any board that is listed here:
https://platformio.org/boards?count=1000&filter%5Bplatform%5D=espressif32

**Comment by BeardedTinker** [comment]
But to add on this, are you sure you are trying to flash firmware.bin file? This error most commonly pops up when you attempt to upload .elf or some other file to board.

**Comment by Tom-Neverwinter** [comment]
aparrently not. esphome instructions kind of blow. 

seems I need to find where esphome is on the rpi for home assistant then compile with the yml file...  then flash with esphome flasher. seems really convoluted

**Comment by BeardedTinker** [comment]
With ESP home you don't need to do anything by hand.
You press one button, select if you want to transfer firmware via WiFi, USB cable or just download and flash it yourself.
If you go with USB cable (device is hooked-up to PC where you have ESPHome open) - just select that and it will compile it for you and upload.
I've never compile anything by hand or even bothered to find where files are.
Secrets are kept outside of it - if you want to do so, or you can have them in same (yaml) file as configuration part.
![image](https://user-images.githubusercontent.com/47822612/145705227-9ea213a9-4894-4bb3-bf87-4e19c695c260.png)

![image](https://user-images.githubusercontent.com/47822612/145705241-2f1e8180-a33b-43f2-ac22-768f186847a8.png)

![image](https://user-images.githubusercontent.com/47822612/145705250-16e3a3f5-2987-4cc0-8798-dd27794b4c3c.png)

Any it's done in minute or two.  Just 3 button presses.

**Comment by Tom-Neverwinter** [comment]
wont work as api isnt setup or configured automatically. same as other variables

**Comment by BeardedTinker** [comment]
If you enable API in ESPHome with `api:` there is nothing else you need to do. Not even password/key is necessary. It's just there for added protection.
After device is rebooted, it will be detected in Home Assistant and in Integrations page you'll have option to add it.
That's it - can't be simpler than that.

The only things you normally need to configure (besides PINs for ESP module itself and sensors you added) is WiFi and if you are not using DHCP, then IP address, subnet and default gateway.
`api:` and `ota`: don't need passwords as I said previously, they are just there for extra security.
Compiling, upload and adding it to Home Assistant is done automatically when you select Upload in ESPHome.

**Comment by Tom-Neverwinter** [comment]
`https://esphome.io/web-api/index.html` then:  `https://esphome.io/components/web_server.html` `no code needed` 

`First up, to use the web server enable it using App.init_web_server() directly from code or using the Web Server Section in ESPHome.` where that is? who knows.... apparently "Web Server Section" is already enabled... yet we need to enable it....

**Comment by BeardedTinker** [comment]
Not sure what's the problem?
If you add following to yaml file:
```
web_server:
  port: 80
```
You can directly access ESP device.
But then again, if you pull values to Home Assistant, why would you need that.
